name: "pinpoint"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pinpoint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 54321:5432
    tmpfs:
      - /var/lib/postgresql/data
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
